/*
 * Created on 2018-09-12 ( Time 17:07:17 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.example.demo.entity;

import java.io.Serializable;

import org.springframework.data.cassandra.core.mapping.PrimaryKey;
import org.springframework.data.cassandra.core.mapping.Table;

import lombok.Getter;
import lombok.Setter;

@Table
@Getter
@Setter
public class Customer implements Serializable {

    private static final long serialVersionUID = 1L;

    @PrimaryKey
    private Long id;

	private String firstName;

	private String lastName;

	public Customer() {
		
	}

}